### ISSUE TITLE
This request has been blocked

### ISSUE THREAD

**Issue by dele** [neodynamic/WebClientPrint-PHP#1]
Hello,
I already installed your Exe file and on your test page works perfectly, but when i install on my domain i saw this error in console on chrome.

Mixed Content: The page at '<URL>' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint '<URL>'. This request has been blocked; the content must be served over HTTPS.

**Comment by dele** [comment]
I'm using cloudflare and $_SERVER['HTTPS'] on/off are not available. Only HTTP_X_FORWARDED_PROTO is available.
I did small change 
                $currentAbsoluteURL = isset($_SERVER['HTTP_X_FORWARDED_PROTO']) ? $_SERVER['HTTP_X_FORWARDED_PROTO'] . "://" : ((@$_SERVER["HTTPS"] == "on") ? "https://" : "http://");


on every file, error are fixed, but still not working

**Comment by neodynamic** [comment]
Please [open a support ticket](https://neodynamic.com/support)
